name: jax
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2022.6.15=py39h06a4308_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cudnn=8.2.1=cuda11.3_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1q=h7f8727e_0
  - pip=22.1.2=py39h06a4308_0
  - python=3.9.12=h12debd9_1
  - readline=8.1.2=h7f8727e_1
  - setuptools=63.4.1=py39h06a4308_0
  - sqlite=3.39.2=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2022a=hda174b7_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - absl-py==1.2.0
    - asttokens==2.0.8
    - astunparse==1.6.3
    - backcall==0.2.0
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - chex==0.1.4
    - colorama==0.4.5
    - commonmark==0.9.1
    - cycler==0.11.0
    - decorator==5.1.1
    - dm-pix==0.3.4
    - dm-tree==0.1.7
    - etils==0.7.1
    - executing==0.10.0
    - ffmpeg==1.4
    - fire==0.4.0
    - flatbuffers==1.12
    - flax==0.6.0
    - fonttools==4.37.1
    - gast==0.4.0
    - gin-config==0.5.0
    - google-auth==2.11.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.47.0
    - h5py==3.7.0
    - htcondor==9.2.0
    - idna==3.3
    - importlib-metadata==4.12.0
    - importlib-resources==5.9.0
    - ipdb==0.13.9
    - ipython==8.4.0
    - jax==0.3.17
    - jaxlib==0.3.15+cuda11.cudnn82
    - jedi==0.18.1
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - libclang==14.0.6
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.5.3
    - matplotlib-inline==0.1.6
    - mediapy==1.1.0
    - msgpack==1.0.4
    - numpy==1.23.2
    - oauthlib==3.2.0
    - opencv-python==4.6.0.66
    - opt-einsum==3.3.0
    - optax==0.1.3
    - packaging==21.3
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.2.0
    - prompt-toolkit==3.0.30
    - protobuf==3.19.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.13.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pyyaml==6.0
    - rawpy==0.17.2
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rich==11.2.0
    - rsa==4.9
    - scipy==1.9.1
    - six==1.16.0
    - stack-data==0.4.0
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.9.1
    - tensorflow-estimator==2.9.0
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - toml==0.10.2
    - toolz==0.12.0
    - traitlets==5.3.0
    - typing-extensions==4.3.0
    - urllib3==1.26.12
    - wcwidth==0.2.5
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - zipp==3.8.1
prefix: /home/grads/hywang26/anaconda3/envs/jax
